"""Utilities for inspecting preprocessing manifests generated by pipeline.py."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Optional

import typer

app = typer.Typer(help="Summarize and validate preprocessing manifests.")


def _resolve_manifest(path: Path) -> Path:
    if path.is_dir():
        path = path / "manifest.json"
    if not path.exists():
        raise typer.BadParameter(f"No manifest found at {path}")
    return path


def _load_manifest(manifest_path: Path) -> dict:
    return json.loads(manifest_path.read_text(encoding="utf-8"))


@app.command()
def summarize(
    location: Path = typer.Argument(..., help="Path to manifest.json or the processed dataset directory."),
    check_files: bool = typer.Option(
        True,
        "--check-files/--no-check-files",
        help="Verify that critical input files referenced by the manifest exist.",
    ),
    show_config: bool = typer.Option(
        False,
        "--show-config",
        help="Print the resolved Hydra config that produced the dataset.",
    ),
):
    """Print a short, human-readable overview of a preprocessing manifest."""
    manifest_path = _resolve_manifest(location)
    data = _load_manifest(manifest_path)

    dataset = data.get("dataset", {})
    typer.echo("📦 Dataset: {}".format(dataset.get("key", "unknown")))
    if dataset.get("description"):
        typer.echo(f"   ↳ {dataset['description']}")

    typer.echo(f"📝 Manifest: {manifest_path}")
    typer.echo(f"   Generated: {data.get('generated_at')}")

    outputs = data.get("outputs", {})
    typer.echo(
        "🪵 Output summary: {} shards, {:.2f} MB, samples={}".format(
            outputs.get("shard_count", 0),
            outputs.get("total_size_bytes", 0) / (1024 * 1024) if outputs.get("total_size_bytes") else 0.0,
            ",".join(outputs.get("sample_dirs", [])) or "n/a",
        )
    )

    stats = data.get("stats", {})
    typer.echo(
        "🧮 Spots processed: {} (failed: {})".format(
            stats.get("total_processed", 0), stats.get("total_failed", 0)
        )
    )

    if show_config:
        typer.echo("\n⚙️  Hydra config (resolved):")
        typer.echo(json.dumps(data.get("hydra_config", {}).get("resolved", {}), indent=2))

    if check_files:
        issues: list[str] = []
        for label, file_info in (
            ("global HVG", data.get("inputs", {}).get("global_hvg")),
            ("HGNC", data.get("inputs", {}).get("hgnc_resource")),
        ):
            if file_info:
                path = Path(file_info.get("path", ""))
                if not path.exists():
                    issues.append(f"Missing {label} file: {path}")
        if issues:
            typer.secho("⚠️  Validation issues detected:", fg=typer.colors.YELLOW)
            for issue in issues:
                typer.echo(f"   - {issue}")
        else:
            typer.secho("✅ Input file check passed", fg=typer.colors.GREEN)


if __name__ == "__main__":
    app()
